version: 2.1

commands:
  run_playbook:
    parameters:
      on_host:
        type: string
        default: localhost
      as_user:
        type: string
        default: circleci
      env:
        type: string
        default: test
      playbook:
        type: string
        default: all.yaml
    steps:
      - run: |
          rsync \
            -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
            -a \
            . \
            << parameters.as_user >>@<< parameters.on_host >>:~/ansible
      - run: |
          ssh \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            << parameters.as_user >>@<< parameters.on_host >> \
            "
              cd ~/ansible
              ansible-playbook \
                -b \
                -i inventory/<< parameters.env >>/static \
                playbooks/<< parameters.env >>/<< parameters.playbook >>
            "

jobs:
  build:
    docker:
      - image: alpine
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build -t nhamcloudlab/circleci:test
  test:
    docker:
      - image: nhamcloudlab/circleci:test
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: true

workflows:
  version: 2
  run_ansible_playbook:
    jobs:
      - build
      - test:
        requires:
        - build

