version: 2.1

commands:
  run_playbook:
    parameters:
      on_host:
        type: string
        default: localhost
      as_user:
        type: string
        default: circleci
      env:
        type: string
        default: test
      playbook:
        type: string
        default: all.yaml
    steps:
      - run: |
          rsync \
            -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" \
            -a \
            . \
            << parameters.as_user >>@<< parameters.on_host >>:~/ansible
      - run: |
          ssh \
            -o StrictHostKeyChecking=no \
            -o UserKnownHostsFile=/dev/null \
            << parameters.as_user >>@<< parameters.on_host >> \
            "
              cd ~/ansible
              ansible-playbook \
                -b \
                -i inventory/<< parameters.env >>/static \
                playbooks/<< parameters.env >>/<< parameters.playbook >>
            "

jobs:
  run_against_staging:
    docker:
      - image: alpine
    steps:
      - run: apk add --update git rsync openssh
      - checkout
      - run_playbook:
          on_host: devops.staging.ehrocks.com
          as_user: ansible
          env: staging

workflows:
  version: 2
  run_ansible_playbook:
    jobs:
      - run_against_staging

